// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	Userid       int32              `json:"userid"`
	Username     string             `json:"username"`
	Passwordhash string             `json:"passwordhash"`
	Email        string             `json:"email"`
	Usertype     int32              `json:"usertype"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
